In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
datos_riqueza_comuna = pd.read_csv("https://raw.githubusercontent.com/leoferres/gitiele356b/main/data/hdi.csv")
datos_poblacion = pd.read_csv("https://raw.githubusercontent.com/leoferres/gitiele356b/main/data/pobXedadCenso.csv")

In [3]:
datos_riqueza_comuna

    comuna       LEI        II        EI    idh       HDI
0    13101  0.791672  0.873137  0.924099  0.807  0.861222
1    13102  0.782817  0.800343  0.713499  0.743  0.764616
2    13103  0.752447  0.750382  0.657961  0.683  0.718874
3    13104  0.784872  0.760697  0.705426  0.707  0.749584
4    13105  0.777236  0.780019  0.673876  0.711  0.742015
5    13106  0.790810  0.784378  0.729145  0.735  0.767604
6    13107  0.726330  0.775631  0.641707  0.737  0.712375
7    13108  0.821551  0.751105  0.722493  0.709  0.763935
8    13109  0.856570  0.835740  0.860235  0.775  0.850780
9    13110  0.773094  0.824255  0.791155  0.804  0.795888
10   13111  0.763582  0.751721  0.668837  0.689  0.726793
11   13112  0.673794  0.758585  0.642574  0.679  0.689951
12   13113  0.890647  0.948908  0.968223  0.883  0.935337
13   13114  0.909774  0.971056  0.988014  0.933  0.955683
14   13115  0.831115  0.921621  0.813262  0.912  0.854046
15   13116  0.759407  0.784503  0.690043  0.657  0.743558
16   13117  0.787707  0.775519  0.697989  0.715  0.752665
17   13118  0.831334  0.842243  0.841346  0.806  0.838293
18   13119  0.768126  0.823406  0.808770  0.782  0.799755
19   13120  0.900363  0.947737  0.993361  0.860  0.946392
20   13121  0.815597  0.767565  0.733783  0.708  0.771589
21   13122  0.749867  0.790376  0.660819  0.743  0.731645
22   13123  0.917316  0.948546  1.044039  0.911  0.968496
23   13124  0.708344  0.764565  0.723853  0.735  0.731874
24   13125  0.667144  0.838734  0.763492  0.782  0.753152
25   13126  0.813982  0.794761  0.686444  0.723  0.762931
26   13127  0.775766  0.742308  0.672305  0.697  0.728831
27   13128  0.725183  0.782950  0.674829  0.709  0.726315
28   13129  0.814219  0.815018  0.747089  0.719  0.791456
29   13130  0.855578  0.851691  0.816075  0.765  0.840925
30   13131  0.767104  0.772013  0.605335  0.679  0.710381
31   13132  0.914831  0.996899  1.078779  0.949  0.994584
32   13201  0.725925  0.773923  0.721415  0.773  0.740045
33   13202  0.749975  0.847558  0.735982  0.807  0.776297
34   13203  0.789578  0.828198  0.654495  0.759  0.753607
35   13301  0.667378  0.787350  0.625280    NaN  0.690036
36   13302  0.683453  0.787269  0.688481    NaN  0.718193
37   13303  0.816336  0.775896  0.629003    NaN  0.735826
38   13401  0.743463  0.762822  0.676397  0.712  0.726599
39   13402  0.742570  0.822340  0.737301    NaN  0.766439
40   13403  0.801109  0.760228  0.601466    NaN  0.715509
41   13404  0.738969  0.776218  0.655095    NaN  0.721614
42   13501  0.787502  0.739201  0.642315    NaN  0.720423
43   13502  0.876923  0.756470  0.617345    NaN  0.742609
44   13503  0.811913  0.766193  0.647025    NaN  0.738340
45   13504  0.809846  0.756324  0.617808    NaN  0.723305
46   13505  0.819107  0.690242  0.556089    NaN  0.679979
47   13601  0.794968  0.802522  0.686845    NaN  0.759548
48   13602  0.740793  0.766459  0.679887    NaN  0.728127
49   13603  0.784525  0.808623  0.736952    NaN  0.776123
50   13604  0.764730  0.738680  0.659196  0.728  0.719437
51   13605  0.785732  0.801915  0.698606    NaN  0.760697

In [4]:
datos_poblacion

        COMUNA EDAD_0A5 EDAD_6A14 EDAD_15A64 EDAD_65YMAS
0         1101        0         0         15           0
1         1101        *         *         54          10
2         1101        *         0         28           *
3         1101        *         7         49           *
4         1101        *         *         26           7
...        ...      ...       ...        ...         ...
180494   15202        *         *          6           4
180495   15202        0         0          0           0
180496   15202        0         0          0           0
180497   15202        *         0          9           *
180498   15202        *         0          0           *

[180499 rows x 5 columns]

Tras realizar la lectura de los archivos, nos damos cuenta que hay valores nulos en el primer archivo y por idosincrásia hay * en el segundo. Dado esto, se procederá a tratar estos valores para que no distorcionen el procesamiento general de los datos.

In [5]:
datos_riqueza_comuna2 = datos_riqueza_comuna.replace(np.nan, datos_riqueza_comuna['idh'].mean())

In [6]:
datos_riqueza_comuna2

    comuna       LEI        II        EI       idh       HDI
0    13101  0.791672  0.873137  0.924099  0.807000  0.861222
1    13102  0.782817  0.800343  0.713499  0.743000  0.764616
2    13103  0.752447  0.750382  0.657961  0.683000  0.718874
3    13104  0.784872  0.760697  0.705426  0.707000  0.749584
4    13105  0.777236  0.780019  0.673876  0.711000  0.742015
5    13106  0.790810  0.784378  0.729145  0.735000  0.767604
6    13107  0.726330  0.775631  0.641707  0.737000  0.712375
7    13108  0.821551  0.751105  0.722493  0.709000  0.763935
8    13109  0.856570  0.835740  0.860235  0.775000  0.850780
9    13110  0.773094  0.824255  0.791155  0.804000  0.795888
10   13111  0.763582  0.751721  0.668837  0.689000  0.726793
11   13112  0.673794  0.758585  0.642574  0.679000  0.689951
12   13113  0.890647  0.948908  0.968223  0.883000  0.935337
13   13114  0.909774  0.971056  0.988014  0.933000  0.955683
14   13115  0.831115  0.921621  0.813262  0.912000  0.854046
15   13116  0.759407  0.784503  0.690043  0.657000  0.743558
16   13117  0.787707  0.775519  0.697989  0.715000  0.752665
17   13118  0.831334  0.842243  0.841346  0.806000  0.838293
18   13119  0.768126  0.823406  0.808770  0.782000  0.799755
19   13120  0.900363  0.947737  0.993361  0.860000  0.946392
20   13121  0.815597  0.767565  0.733783  0.708000  0.771589
21   13122  0.749867  0.790376  0.660819  0.743000  0.731645
22   13123  0.917316  0.948546  1.044039  0.911000  0.968496
23   13124  0.708344  0.764565  0.723853  0.735000  0.731874
24   13125  0.667144  0.838734  0.763492  0.782000  0.753152
25   13126  0.813982  0.794761  0.686444  0.723000  0.762931
26   13127  0.775766  0.742308  0.672305  0.697000  0.728831
27   13128  0.725183  0.782950  0.674829  0.709000  0.726315
28   13129  0.814219  0.815018  0.747089  0.719000  0.791456
29   13130  0.855578  0.851691  0.816075  0.765000  0.840925
30   13131  0.767104  0.772013  0.605335  0.679000  0.710381
31   13132  0.914831  0.996899  1.078779  0.949000  0.994584
32   13201  0.725925  0.773923  0.721415  0.773000  0.740045
33   13202  0.749975  0.847558  0.735982  0.807000  0.776297
34   13203  0.789578  0.828198  0.654495  0.759000  0.753607
35   13301  0.667378  0.787350  0.625280  0.762865  0.690036
36   13302  0.683453  0.787269  0.688481  0.762865  0.718193
37   13303  0.816336  0.775896  0.629003  0.762865  0.735826
38   13401  0.743463  0.762822  0.676397  0.712000  0.726599
39   13402  0.742570  0.822340  0.737301  0.762865  0.766439
40   13403  0.801109  0.760228  0.601466  0.762865  0.715509
41   13404  0.738969  0.776218  0.655095  0.762865  0.721614
42   13501  0.787502  0.739201  0.642315  0.762865  0.720423
43   13502  0.876923  0.756470  0.617345  0.762865  0.742609
44   13503  0.811913  0.766193  0.647025  0.762865  0.738340
45   13504  0.809846  0.756324  0.617808  0.762865  0.723305
46   13505  0.819107  0.690242  0.556089  0.762865  0.679979
47   13601  0.794968  0.802522  0.686845  0.762865  0.759548
48   13602  0.740793  0.766459  0.679887  0.762865  0.728127
49   13603  0.784525  0.808623  0.736952  0.762865  0.776123
50   13604  0.764730  0.738680  0.659196  0.728000  0.719437
51   13605  0.785732  0.801915  0.698606  0.762865  0.760697

In [7]:
datos_poblacion2 = datos_poblacion.replace('*',0)

Ahora procederemos a seleccionar solamente los datos de nuestro interés. Es decir, las comunas correspondientes a la región Metropolitana

In [8]:
datos_poblacion = datos_poblacion2['COMUNA'].isin(datos_riqueza_comuna['comuna'])

In [9]:
datos_poblacion =datos_poblacion2.loc[datos_poblacion == True]

In [10]:
datos_poblacion.dtypes

COMUNA          int64
EDAD_0A5       object
EDAD_6A14      object
EDAD_15A64     object
EDAD_65YMAS    object
dtype: object

Como las edades están registradas como objetos, pasaremos a hacer la conversión a enteros

In [11]:
def to_int(val):
    try:
        value = int(float(val))
    except ValueError:
        value = ""
    return value

datos_poblacion['EDAD_0A5'] = datos_poblacion['EDAD_0A5'].map(to_int)
datos_poblacion['EDAD_6A14'] = datos_poblacion['EDAD_6A14'].map(to_int)
datos_poblacion['EDAD_15A64'] = datos_poblacion['EDAD_15A64'].map(to_int)
datos_poblacion['EDAD_65YMAS'] = datos_poblacion['EDAD_65YMAS'].map(to_int)

<ipython-input-11-22bfa687cbfb>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_poblacion['EDAD_0A5'] = datos_poblacion['EDAD_0A5'].map(to_int)
<ipython-input-11-22bfa687cbfb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_poblacion['EDAD_6A14'] = datos_poblacion['EDAD_6A14'].map(to_int)
<ipython-input-11-22bfa687cbfb>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_poblacion['EDAD_15A64'] = datos_poblacion['EDAD_15A64'].map(to_int)
<ipython-input-11-22bfa687cbfb>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_poblacion['EDAD_65YMAS'] = datos_poblacion['EDAD_65YMAS'].map(to_int)

In [12]:
datos_poblacion = datos_poblacion.groupby('COMUNA').sum()

In [13]:
datos_poblacion

        EDAD_0A5  EDAD_6A14  EDAD_15A64  EDAD_65YMAS
COMUNA
13101      22618      23769      323893        28936
13102       5907       8703       53650         9273
13103       9719      14745       89915        16011
13104       8730      12629       85791        16819
13105      12071      18633      109501        19321
13106       9422      12110      105479        16724
13107       8465      13508       66093         9016
13108       7195       8357       72314        10749
13109       6162       8953       61118        12715
13110      24131      37044      251149        45185
13111       8539      12728       79967        13453
13112      15156      23996      119328        15513
13113       5479       9402       62159        13321
13114      17548      23766      203649        44861
13115       7818      15397       73112         7582
13116       7609      11098       67754        11420
13117       6532       9574       64747        13745
13118       7347      10177       79768        16742
13119      32393      56836      370501        45224
13120      13414      15287      146549        29777
13121       6654       9736       68628        14007
13122      16914      29019      167190        23945
13123       8280       8303      101578        21805
13124      17228      27450      162552        18304
13125      15114      28469      150827         9997
13126       7412      10515       76222        14010
13127      11088      15726      109346        19301
13128      11698      17951       99893        14152
13129       6039       8519       64126        13509
13130       7556       9325       76224        13628
13131       6064       8842       54971        11905
13132       6219       8227       54307        14511
13201      41148      69347      401186        39781
13202       1932       3141       18189         2492
13203       1034       1768       11950         1755
13301      13738      21129       98912         7813
13302       9327      14511       69124         5262
13303       1452       2061       13195         1804
13401      23331      38188      206389        24187
13402       7296      11651       66360         7667
13403       1700       2991       17442         2072
13404       5240       8900       49671         6332
13501       8937      14139       83196        13342
13502        309        489        4472          600
13503       2284       3709       21872         3514
13504        785       1365        9071         1166
13505        633       1075        6126         1113
13601       5619       8762       51047         6648
13602       2865       4375       24123         3363
13603       2521       4353       24431         3381
13604       5140       7296       43416         5061
13605       6966      11202       61263         8432

In [14]:
datos_poblacion['Total']=datos_poblacion.iloc[:,0:].sum(axis=1)

In [15]:
datos_poblacion

        EDAD_0A5  EDAD_6A14  EDAD_15A64  EDAD_65YMAS   Total
COMUNA
13101      22618      23769      323893        28936  399216
13102       5907       8703       53650         9273   77533
13103       9719      14745       89915        16011  130390
13104       8730      12629       85791        16819  123969
13105      12071      18633      109501        19321  159526
13106       9422      12110      105479        16724  143735
13107       8465      13508       66093         9016   97082
13108       7195       8357       72314        10749   98615
13109       6162       8953       61118        12715   88948
13110      24131      37044      251149        45185  357509
13111       8539      12728       79967        13453  114687
13112      15156      23996      119328        15513  173993
13113       5479       9402       62159        13321   90361
13114      17548      23766      203649        44861  289824
13115       7818      15397       73112         7582  103909
13116       7609      11098       67754        11420   97881
13117       6532       9574       64747        13745   94598
13118       7347      10177       79768        16742  114034
13119      32393      56836      370501        45224  504954
13120      13414      15287      146549        29777  205027
13121       6654       9736       68628        14007   99025
13122      16914      29019      167190        23945  237068
13123       8280       8303      101578        21805  139966
13124      17228      27450      162552        18304  225534
13125      15114      28469      150827         9997  204407
13126       7412      10515       76222        14010  108159
13127      11088      15726      109346        19301  155461
13128      11698      17951       99893        14152  143694
13129       6039       8519       64126        13509   92193
13130       7556       9325       76224        13628  106733
13131       6064       8842       54971        11905   81782
13132       6219       8227       54307        14511   83264
13201      41148      69347      401186        39781  551462
13202       1932       3141       18189         2492   25754
13203       1034       1768       11950         1755   16507
13301      13738      21129       98912         7813  141592
13302       9327      14511       69124         5262   98224
13303       1452       2061       13195         1804   18512
13401      23331      38188      206389        24187  292095
13402       7296      11651       66360         7667   92974
13403       1700       2991       17442         2072   24205
13404       5240       8900       49671         6332   70143
13501       8937      14139       83196        13342  119614
13502        309        489        4472          600    5870
13503       2284       3709       21872         3514   31379
13504        785       1365        9071         1166   12387
13505        633       1075        6126         1113    8947
13601       5619       8762       51047         6648   72076
13602       2865       4375       24123         3363   34726
13603       2521       4353       24431         3381   34686
13604       5140       7296       43416         5061   60913
13605       6966      11202       61263         8432   87863

Para el estudio, simplemente se utilizará el dataset del MinCiencia correspondiente a la primera dosis, dado que estos abarcan las mismas personas que se vacunarán por segunda vez.

In [ ]:
vacunacion_1ra = pd.read_csv("https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto81/vacunacion_comuna_edad_1eraDosis.csv")

In [ ]:
vacunacion_1ra

In [ ]:
vacunacion_1ra.dtypes

In [ ]:
datos_riqueza_comuna2.dtypes

Vemos que hay filas que poses solamente valores nulos. Procederemos a eliminarlos y a seleccionar solamente los correspondientes a las comunas de la región Metropolitana

In [ ]:
vacunacion_1ra = vacunacion_1ra[vacunacion_1ra['Codigo comuna'].notna()]

In [ ]:
comuna_1ra = vacunacion_1ra['Codigo comuna'].isin(datos_riqueza_comuna['comuna'])

In [ ]:
comuna_1ra =vacunacion_1ra.loc[comuna_1ra == True]

In [ ]:
comuna_1ra

Juntaremos los totales vacunados según grupo etario

In [ ]:
comuna_1ra = comuna_1ra.drop(['Region','Codigo region', 'Comuna'],axis=1)

In [ ]:
comuna_total = comuna_1ra

In [ ]:
comuna_total['EDAD_15A64'] = comuna_total.iloc[:,2:52].sum(axis=1)

In [ ]:
comuna_total['EDAD_65YMAS'] = comuna_total.iloc[:,52:68].sum(axis=1)

In [ ]:
comuna_total

In [ ]:
comuna_total2 = comuna_total.drop(comuna_total.iloc[:,2:68], axis=1)
comuna_total2 = comuna_total2.rename(columns={'Codigo comuna':'COMUNA', 'EDAD_15A64':'Vacunados_15A64', 'EDAD_65YMAS':'Vacunados_65YMAS'})

In [ ]:
comuna_total2

In [ ]:
datos_poblacion.reset_index()

Como no hay registros de vacunados de gente menor a 15 años, los grupos etarios de EDAD_0A5 y EDAD_6A14 no serán considerados para el estudio.

In [ ]:
DATOS = datos_poblacion.drop(['EDAD_0A5','EDAD_6A14'], axis=1)
DATOS.reset_index()

In [ ]:
DATOS2 =pd.merge(DATOS, comuna_total2, on=['COMUNA'], how='left')
DATOS2

La columna 'Total' representa la población de la comuna según el censo, mientras que la columna 'Población' representa la cantidad de habitantes por comuna según los registros del MinCiencia. Como estos datos no coinciden, no es posible realizar una comparación entre los los habitantes y vacunados de los distintos grupos etarios de cada comuna. Por esto mismo, solamente se utilizará la columna 'Población' y se hará una relación porcentual entre los vacunados por grupo etario y el total de vacunados, además de la relación entre el total de vacunados y la población de la comuna

In [ ]:
DATOS2['Total_Vacunados'] = DATOS2['Vacunados_15A64']+DATOS2['Vacunados_65YMAS']
DATOS2['%Vacunados'] = DATOS2['Total_Vacunados']/DATOS2['Poblacion']*100

In [ ]:
DATOS2['HDI']=datos_riqueza_comuna2['HDI']
DATOS2

Ahora que ya se tienen todos la información necesaria recopilada en un solo dataframe, procederemos a hacer el estudio de correlación

In [ ]:
DATOS2.corr('pearson')

In [ ]:
import seaborn as sb

sb.lmplot(x = "HDI",
            y = "%Vacunados", 
            ci = None,
            data = DATOS2)

Respecto al gráfico anterior, el cual presenta el porcentaje de vacunados de las distintas comunas según su índice de desarrollo humano, se puede ver que existe una correlación positiva entre el índice de desarrollo humano y el porcentaje de la población que se vacuna, lo cual da una intuición para indicar que entre más rica sea una comuna, mayor será el porcentaje de gente que vive en ella que se vacunará, independiente de la edad.

In [ ]:
sb.lmplot(x = "HDI",
            y = "Vacunados_65YMAS", 
            ci = None,
            data = DATOS2)

En el gráfico recién mostrado, el cual representa la cantidad de vacunados de 65 años y más respecto a la riqueza de la comuna, al igual que el caso anterior, igual se aprecia una correlación positiva entre estas dos variables, lo cual permite indicar que entre mayor sea la riqueza de una comuna, mayor será la cantidad de gente de 65 años y más que se vacunará. Sin embargo, no todas las comunas tienen la misma cantidad de población de 65 años y más, por lo que se procederá a realizar la comparación entre la riqueza de la comuna y el porcentaje de vacunados de 65 años y más respecto al total de la población de la comuna.

In [ ]:
DATOS2['%Vacunados_15A64']=DATOS2['Vacunados_15A64']/DATOS2['Poblacion']*100
DATOS2['%Vacunados_65YMAS']=DATOS2['Vacunados_65YMAS']/DATOS2['Poblacion']*100

In [ ]:
sb.lmplot(x = "HDI",
            y = "%Vacunados_15A64", 
            ci = None,
            data = DATOS2)
sb.lmplot(x = "HDI",
            y = "%Vacunados_65YMAS", 
            ci = None,
            data = DATOS2)

Los dos gráficos anteriores muestran la relación entre el porcentaje de vacunados de los dos grupos etarios y el índice de desarrollo humano. Como se puede ver, existe una correlación positiva en ambos, pero en el caso de la población de 65 años y más, la pendiente de la recta es aúun mayor. Esto puede dar un indicio para aseverar que a mayor riqueza riqueza de la comuna, el aumento porcentual de la gente que se vacuna de 65 años y más es mayor que la de la gente entre 15 y 64 años. Una de las razones que podría justificar esto es que efectivamente a mayor índice de desarrollo humano tenga la comuna, hay más cantidad de gente viviendo en ellas que es de 65 años y más. Sin embargo, como los datos del censo no coinciden con los datos del MinCiencia, no podemos corroborarlo en su totalidad, pero con los datos que se tienen, se logra tener un indicio mayor para poder aseverar que el efecto de que las comunas más ricas se vacunaron primero son las que tienen mayor promedio de edad.